<?php	return array (
  'SP_SITE_ADMIN_URL_PASSWORD' => '',
  'SP_DEFAULT_THEME' => 'simplebootx',
  'DEFAULT_THEME' => 'simplebootx',
  'SP_ADMIN_STYLE' => 'flat',
  'URL_MODEL' => '2',
  'URL_HTML_SUFFIX' => 'html',
  'UCENTER_ENABLED' => 1,
  'COMMENT_NEED_CHECK' => 0,
  'COMMENT_TIME_INTERVAL' => 60,
  'MOBILE_TPL_ENABLED' => 0,
  'HTML_CACHE_ON' => true,
  'SP_MAIL_ADDRESS' => 'noreply@huosdk.com',
  'SP_MAIL_SENDER' => '官方验证邮箱',
  'SP_MAIL_SMTP' => 'mail.huosdk.com',
  'SP_MAIL_SMTP_PORT' => '25',
  'SP_MAIL_LOGINNAME' => 'noreply@huosdk.com',
  'SP_MAIL_PASSWORD' => 'HuoSdk#1',
);