<?php
return array (
  'app' => 'Admin',
  'model' => 'Operate',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '运营中心',
  'icon' => 'th',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Game',
      'action' => 'gameList',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '游戏管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Gift',
      'action' => 'giftList',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '礼包管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Subpackage',
      'action' => 'qudaoindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '一键分包',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Member',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '玩家管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '渠道管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '5',
    ),
  ),
);