<?php
return array (
  'app' => 'Admin',
  'model' => 'Agent',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '数据中心',
  'icon' => '',
  'remark' => '',
  'listorder' => '1',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'cps',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => 'CPS数据统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'cpa',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => 'CPA数据统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'register',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '注册登陆统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Agent',
      'action' => 'channel',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '渠道效果统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Pay',
      'action' => 'default',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'SDK充值管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Pay',
      'action' => 'payUser',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '充值用户列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);