<?php
return array (
  'app' => 'Admin',
  'model' => 'Spread',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '推广渠道后台',
  'icon' => '',
  'remark' => '',
  'listorder' => '4',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Spreaddata',
      'action' => 'sregindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '注册用户列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Spreaddata',
      'action' => 'spayindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '充值数据列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Spreaddata',
      'action' => 'spayuserindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '充值用户列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Spreaddata',
      'action' => 'sloginindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '登陆用户列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Spreaddata',
      'action' => 'sremainindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '用户留存统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Spreaddata',
      'action' => 'cpseffectindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'CPS效果统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Spreaddata',
      'action' => 'cpaeffectindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => 'CPA效果统计',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);